[mypy]
ignore_missing_imports = True
python_version = 3.13
follow_imports = skip
check_untyped_defs = False
warn_unused_ignores = False
warn_redundant_casts = False
warn_no_return = False
warn_return_any = False
disallow_untyped_defs = False
no_implicit_optional = False
disable_error_code = call-overload,assignment,misc,var-annotated,operator,override,union-attr,arg-type
exclude = ^venv/|^tests/
